### ISSUE TITLE
question about for from_png_bytes, why this function only for linux?

### ISSUE THREAD

**Issue by hunjixin** [sidit77/betrayer#6]
[from_png_bytes](https://github.com/sidit77/betrayer/blob/5f5c4bc07dd97ecc8f8a5f384aede4acf1e4e50d/src/lib.rs#L195-L199)  can this function work on macos?  macos only accept rgba

**Comment by sidit77** [comment]
First of all, icons aren't implemented for MacOS yet, because I got kinda burnt out for several reasons:

- I don't own a Mac, so I had to develop in a barely working VM.
- I found Apple's documentation really bad
- Rust support for MacOS APIs is mostly an immature community effort

In general I kinda followed winit for the icon API. 

The from_png_data function in particular exists for Linux because the icons must be written to the disc as png before they can be used. So the function essentially exists to eliminate an unnecessary decode->encode step if your icons are already encoded as pngs.

**Comment by hunjixin** [comment]
i know, thanks.
